version: 2

# workflow to update the submodules on a monthly interval using dependabot
# more information - https://stackoverflow.com/a/73229032/6623589
updates:
  - package-ecosystem: gitsubmodule
    schedule:
      interval: "monthly"
    directory: /
